### ISSUE TITLE
To Do List

### ISSUE THREAD

**Issue by razvanfilea** [TheLuckyCoder/Emerald-Mod-PE#1]
- Improve the Emerald Slab
- Emerald Stairs
- Emerald Bow (crashes when used)
- Emerald Trees

**Comment by Khristian-kun** [comment]
How to teleport to emerald dimension?

**Comment by razvanfilea** [comment]
In a useOn function we just need to call play->changeDimension(DimensionId::Emerald);
But it crashes

**Comment by Khristian-kun** [comment]
also if its hooked by Nether one?

**Comment by razvanfilea** [comment]
@Khristian-kun no, if we try to teleport to nether, everything will work normally, I this is what you were meaning

**Comment by Khristian-kun** [comment]
you didnt defined the terrain, for that, it DOESNT HAVE any block for spawn...

**Comment by Khristian-kun** [comment]
maybe this code will help you

**Comment by razvanfilea** [comment]
@Khristian-kun I hope, that you can help me. I really don't know how to set the terrain

**Comment by Khristian-kun** [comment]
https://github.com/enoter/Custom-Dimension-MCPE/

**Comment by Khristian-kun** [comment]
Also, last commit have FGITs while compiling...

**Comment by razvanfilea** [comment]
@Khristian-kun I know I will commit the fixes in 5 min

**Comment by Khristian-kun** [comment]
Also Emerald and Steel crashes when use, why not to hook it as a normal flint and steel one?

**Comment by razvanfilea** [comment]
@Khristian-kun it's crashing because of the Entity header, we need a new one.

**Comment by Khristian-kun** [comment]
Ohh ok

**Comment by CheatBoss** [comment]
0.15.2.1?

**Comment by Johnmacrocraft** [comment]
@TheLuckyCoder Is this mod dead now? If so, why? I really love it.

**Comment by razvanfilea** [comment]
@Johnmacrocraft why should it be dead? I'm almost ready with updating for 1.0.7
I will try the release the update later today if not, tomorrow

**Comment by Johnmacrocraft** [comment]
@TheLuckyCoder Really? Yay, now I can enjoy these emerald stuffs again! :D :) ;)
