### ISSUE TITLE
Invisible textures

### ISSUE THREAD

**Issue by ara2am** [TheLuckyCoder/Emerald-Mod-PE#3]
i use mcpe 0.15.2 and 0.15.3. And the last version of free blocklauncher (you can download it in google play), but in every addons i can not see texture of items. I check all of your addons. @TheLuckyCoder if you addons work good can you send your version of block launcher and of MCPE, I will be glad to know it.

**Comment by razvanfilea** [comment]
This bug happens if the BlockLauncher permission haven't been manually granted on Android 6.0 or above.

I will implement an dialog that will request the permission in order to remove confusion
