### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by ara2am** [TheLuckyCoder/Emerald-Mod-PE#7]
@TheLuckyCoder How can i contact with you? All my social networks there https://vk.com/aradam?w=wall210738902_4130

**Comment by razvanfilea** [comment]
You can contact me by sending me an email at contact@theluckycoder.net. But I would prefer that you contact me on Twitter: Vezi The Lucky Coder (@theluckycoder): https://twitter.com/theluckycoder?s=09

**Comment by ara2am** [comment]
@TheLuckyCoder , ok, i am using twitter first time and i am https://twitter.com/ara2am . Send message for me, because i havent permissions to write you.
